# Debug 调试模式
debug: false
# 本地静态文件使用jsdelivr的min版本加速 https://www.jsdelivr.com/features
# 默认使用 https://npm.elemecdn.com/hexo-theme-volantis@<%- theme.info.theme_version %>/source/js/*.min.js 的CDN压缩版本(min.js)，注意版本号对应关系！！可以通过修改以下配置项覆盖
# 开发者注意 cdn.enable 设置为 false
cdn:
  enable: false
  prefix: # CDN 前缀，为空使用默认值，链接最后不加 "/",例如： https://cdn.jsdelivr.net/gh/volantis-x/volantis-x.github.io@gh-page 填写最后编译生成的源码CDN地址前缀，此路径下应该含有/js与/css目录,该配置默认值是："https://npm.elemecdn.com/hexo-theme-volantis@"+ theme.info.theme_version +"/source"
  # 以下配置可以覆盖 cdn.prefix,配置项的值可以为空，但是要使用CDN必须依据路径填写配置项的键
  set:
    js:
      app: #/js/app.js
    css:
      style: #/css/style.css # (异步加载样式)

seo:
  # When there are no keywords in the article's front-matter, use tags as keywords.
  use_tags_as_keywords: true
  # When there is no description in the article's front-matter, use excerpt as the description.
  use_excerpt_as_description: true
  robots:
    home_first_page: index,follow
    home_other_pages: noindex,follow
    archive: noindex,follow
    category: noindex,follow
    tag: noindex,follow
    # robots can be written in front-matter

navbar:
  visiable: auto # always, auto
  logo: # choose [img] or [icon + title]
    img: '' #https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/Logo-NavBar@3x.png
    icon:
    title: "Odomu's <sup style='color:#ff9800'>Blog</sup>"
  menu:
    - name: 博客
      icon: fad fa-flag faa-tada fa-fw
      url: /
      target: _self
    - name: 分类
      icon: fad fa-folder fa-fw
      url: categories/
    - name: 归档
      icon: fad fa-list-alt fa-fw
      url: archives/
    - name: 友链
      icon: fad fa-link fa-fw
      url: friends/
    - name: 关于
      icon: fad fa-bath fa-fw
      url: about/
    - name: 更多
      icon: fad fa-fan fa-spin fa-fw
      rows:
        - name: 说说
          icon: fad fa-user-tie fa-fw
          url: artitalk/
        - name: 暗黑模式
          icon: fad fa-moon fa-fw
          toggle: darkmode
        - name: Github
          icon: fab fa-github fa-fw
          url: https://github.com/odomu/
  search: Search...   # Search bar placeholder

cover:
  height_scheme: full # full, half
  layout_scheme: search # blank (留白), search (搜索), dock (坞), featured (精选), focus (焦点)
  display:
    home: true
    archive: false
    others: true # can be written in front-matter 'cover: true'
  background: https://uploadbeta.com/api/pictures/random/?key=BingEverydayWallpaperPicture
  # background: https://bing.ioliu.cn/v1/rand?w=1920&h=1200
  logo: # https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/Logo-Cover@3x.png
  title: "Odomu's Blog"
  subtitle: '一个记录个人生活和笔记的博客'
  search: 输入你想要知道的事情 # search bar placeholder
  features:
  - name: 文章
    img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4f0.svg
    url: /
  - name: 归档
    img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f5c3.svg
    url: /archives/
  - name: 关于
    img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f389.svg
    url: about/

article:
  preview:
    scheme: landscape # landscape
    # pin icon for post
    pin_icon: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4cc.svg
    # auto generate title if not exist
    auto_title: true # false, true
    # auto generate excerpt if not exist
    auto_excerpt: true # false, true
    author: true
    # show readmore button
    readmore: always # auto, always
    # 文章详情页面的文章卡片本体布局方案
  body:
    # 文章顶部信息
    # 从 meta_library 中取
    top_meta: [author, wordcount, category, date] #启用评论数量需在此添加
    # ----------------
    # 文章页脚组件
    footer_widget:
      # ----------------
      # 参考资料、相关资料等 (for layout: post/docs)
      references:
        title: 参考资料
        icon: fa-solid fa-quote-left
        # 在 front-matter 中:
        #   references:
        #     - title: 某篇文章
        #       url: https://
        # 即可显示此组件。
      # ----------------
      # 相关文章，需要安装插件 (for layout: post)
      # npm i hexo-related-popular-posts
      related_posts:
        enable: true
        title: 相关文章
        icon: fa-solid fa-bookmark
        max_count: 5
        # 设为空则不使用文章头图
        placeholder_img: https://uploadbeta.com/api/pictures/random/?key=BingEverydayWallpaperPicture
      # ----------------
      # 版权声明组件 (for layout: post)
      copyright:
        enable: false
        permalink: '本文永久链接是：'
        content:
          - '博客内容遵循 署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0) 协议'
          - permalink
    # 文章底部信息 从 meta_library 中取
    bottom_meta: [updated, category, tags, share]
    # meta library
    meta_library:
      # 默认文章作者（可在 _data/author.yaml 中增加其他作者，并在 front-matter 中设置）
      # https://volantis.js.org/advanced-settings/#多人协同
      author:
        avatar: https://avatars.githubusercontent.com/u/50035498?s=400&u=d41946e4d7523ed5cf9bf33c4bbb3157d20ba98e&v=4
        name: Odomu
        url: https://github.com/odomu/
      # 文章创建日期
      date:
        icon: fad fa-edit BELIZEHOLE fa-fw
        title: '发布于：'
        format: 'll' # 日期格式 http://momentjs.com/docs/
      updated:
        icon: fad fa-edit GREENSEA fa-fw
        title: '更新于：'
        format: 'll' # 日期格式 http://momentjs.com/docs/
      # 文章分类
      category:
        icon: fad fa-folder-open EMERALD fa-fw
      # 文章浏览计数
      counter:
        icon: fa-solid fa-eye
        unit: '次浏览'
      # 文章评论数量：支持 valine和waline
      valinecount:
        icon: fa-solid fa-comment-dots
        desc: '' # 条评论
      walinecount:
        icon: fa-solid fa-comment-dots
        desc: '' # 条评论
      # 文章字数和阅读时长 hexo-wordcount
      wordcount:
        icon_wordcount: fad fa-hourglass-half BELIZEHOLE fa-fw
        icon_duration: fad fa-hourglass-half BELIZEHOLE fa-fw
      # 文章标签
      tags:
        icon: fad fa-hashtag CARROT fa-fw
      # 分享
      share:
        - id: qq
          img:  /media/org.volantis/logo/128/qq.png #  https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/qq.png
        - id: qzone
          img: /media/org.volantis/logo/128/qzone.png #  https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/qzone.png
        - id: weibo
          img: /media/org.volantis/logo/128/weibo.png #  https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/weibo.png
        - id: qrcode # 当id为qrcode时需要安装插件  npm i hexo-helper-qrcode
          img: /media/org.volantis/logo/128/wechat.png #  https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/wechat.png
        - id: # telegram
          img: # /media/org.volantis/logo/128/telegram.png #  https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/telegram.png


comments:
   service:
#   valine:
#     path: /
#     appId: 9sazm8qFY8fkdXTt8B8smopI-MdYXbMMI
#     appKey: WL9fTHWmTb8ndeJTSkmWwzK8
#     serverURLs: https://9sazm8qf.api.lncldglobal.com
#     requiredFields: [ nick ]

sidebar:
  for_page: [blogger, guide, lastupdate, webinfo]
  for_post: [toc]
  widget_library:
    # blogger info widget
    blogger:
      class: blogger
      display: [desktop, mobile] # [desktop, mobile]
      avatar: https://bing.ioliu.cn/v1/rand?w=1920&h=1200
      shape: rectangle # circle, rectangle
      url: /about/
      title:
      subtitle:
      jinrishici: true # Poetry Today. You can set a string, and it will be displayed when loading fails.
      social:
        - icon: fa-solid fa-rss
          url: /atom.xml
        - icon: fa-solid fa-envelope
          url: mailto:1374415225@qq.com
        - icon: fab fa-github
          url: https://github.com/odomu/
        - icon: fa-solid fa-headphones-alt
          url: /
    toc:
      class: toc
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fad fa-list CARROT fa-fw
        title: 本文目录
      list_number: true
      min_depth: 2
      max_depth: 5
    # category widget
    category:
      class: category
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fa-solid fa-folder-open
        title: 文章分类
        url: categories/
    # 文档导航
    guide:
      class: grid
      display: [ desktop, mobile ] # [desktop, mobile]
      header:
        icon: fad fa-map-signs POMEGRANATE fa-fw
        title: 站内导航
      fixed: true # 固定宽度
      rows:
        - name: 文章归档
          icon: fad fa-books GREENSEA fa-fw
          url: archives/
        - name: 文章分类
          icon: fad fa-folder-open PETERRIVE fa-fw
          url: categories/
        - name: 文章标签
          icon: fad fa-tags GREENSEA fa-fw
          url: tags/
        - name: 关于本站
          icon: fad fa-bath NEPHRITIS fa-fw
          url: about/
        - name: 友情链接
          icon: fad fa-link PETERRIVE fa-fw
          url: friends/
        - name: 文章说说
          icon: fad fa-user-tie GREENSEA fa-fw
          url: shuoshuo/
    # webinfo widget
    webinfo:
      class: webinfo
      display: [ desktop ]
      header:
        icon: fad fa-award NEPHRITIS fa-fw
        title: 站点信息
      type:
        article:
          enable: true
          text: '文章数目：'
          unit: '篇'
        runtime:
          enable: true
          data: '2022/01/01'    # 填写建站日期
          text: '已运行时间：'
          unit: '天'
        wordcount:
          enable: true
          text: '本站总字数：'   # 需要启用 wordcount
          unit: '字'
        visitcounter:
          service: leancloud  # busuanzi, leancloud
          siteuv:
            enable: true
            text: '本站访客数：'
            unit: '人'
          sitepv:
            enable: true
            text: '本站总访问量：'
            unit: '次'
        lastupd:
          enable: true
          friendlyShow: true    # 更友好的时间显示
          text: '最后活动时间：'
          unit: '日'
    # lastupdate widget
    lastupdate:
      class: lastupdate
      display: [ desktop, mobile ]
      header:
        icon: fa-solid fa-clock WISTERIA
        title: 最近更新

rightmenu:
  enable: true
  faicon: fa-duotone PETERRIVE
  layout: [ home, hr, archives, about, source, hr, print, darkmode, reading, music ]
  print:
    icon: fa-duotone fa-print TURQUOISE
  darkmode:
    icon: fa-duotone fa-eclipse-alt WISTERIA
  reading:
    icon: fa-duotone fa-book-open EMERALD
  # 自定义内容
  archives:
    name: '文章归档'
    icon: fal fa-books GREENSEA
    url: archives/
  about:
    name: '关于本站'
    icon: fal fa-bath NEPHRITIS
    url: about/
  source:
    name: '本站源码'
    icon: fal fa-code-branch GREENSEA
    url: https://github.com/odomu/odomuBlog

site_footer:
  layout: [ aplayer, social, analytics, copyright ]
  copyright: "[Copyright © 2021-2099 Odomu's Blog](https://github.com/odomu/)"
  social:
    # rss
    - icon: fas fa-rss
      url: atom.xml
    # email
    - icon: fas fa-envelope
      url: mailto:1374415225@qq.com
    # github
    - icon: fas fa-github
      url: https://github.com/odomu
    # music
    - icon: fas fa-headphones-alt
      url: https://music.163.com/#/user/home?id=63035382

custom_css:
  cursor:
    enable: true
    text: /media/cursor/text.png # https://cdn.jsdelivr.net/gh/inkss/common@1/cursor/text.png
    pointer: /media/cursor/pointer.png # https://cdn.jsdelivr.net/gh/inkss/common@1/cursor/pointer.png
    default: /media/cursor/left_ptr.png # https://cdn.jsdelivr.net/gh/inkss/common@1/cursor/left_ptr.png
    not-allowed: /media/cursor/circle.png # https://cdn.jsdelivr.net/gh/inkss/common@1/cursor/circle.png
    zoom-out: /media/cursor/zoom-out.png # https://cdn.jsdelivr.net/gh/inkss/common@1/cursor/zoom-out.png
    zoom-in: /media/cursor/zoom-in.png # https://cdn.jsdelivr.net/gh/inkss/common@1/cursor/zoom-in.png
    grab: /media/cursor/openhand.png # https://cdn.jsdelivr.net/gh/inkss/common@1/cursor/openhand.png
  font_smoothing: true # font-smoothing for webkit
  sidebar:
    effect: [shadow] # [shadow, floatable, blur]
  body:
    effect: [shadow] # [shadow, floatable, blur]
  fontfamily:
    logofont:
      fontfamily: 'Dosis, "PingFang SC", "Microsoft YaHei", Helvetica, Arial'
      name: 'Dosis'
      url: https://cdn.jsdelivr.net/gh/volantis-x/cdn-fonts@20.5.30/Dosis/Dosis-Medium.ttf
      weight: normal
      style: normal
    bodyfont:
      fontfamily: 'Dosis, "PingFang SC", "Microsoft YaHei", Helvetica, Arial'
      name: 'Dosis'
      url: https://cdn.jsdelivr.net/gh/volantis-x/cdn-fonts@20.5.30/Dosis/Dosis-Medium.ttf
      weight: normal
      style: normal

plugins:
  # 代码高亮
  code_highlight: highlightjs # highlightjs or prismjs
  # highlight.js
  highlightjs:
    copy_code: true
    # 如果开启 js, hexo.config.highlight.enable 需要设置为 false
    js: #https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.1.0/build/highlight.min.js # Please set hexo.config.highlight.enable = false !!!
    css: https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.1.0/build/styles/default.min.css
    # more: https://www.jsdelivr.com/package/npm/highlight.js?path=styles
  # Artitalk https://artitalk.js.org
  # 配置过程请参考：https://artitalk.js.org/doc.html
  # 使用过旧版本的请修改Leancloud shuoshuo class部分列名：https://artitalk.js.org/release.html
  # 除appID和appKEY外均为选填项
  artitalk:
    # Set `plugins: ["artitalk"]` to enable in front-matter
    # 不支持 Pjax
    # 配置项按照yml格式继续填写即可
    js: https://cdn.jsdelivr.net/npm/artitalk
    appId: YUYnaaTyd8MI9tivdEx2Ofmo-MdYXbMMI # your appID
    appKey: 3a4spbiv5QkvDhhVsXfknvRg # your appKEY
    # serverURL:  #leancloud绑定的api访问域名，使用国际版的话不需要填写
    # lang: # 语言设置，zh为汉语，en为英语，es为西班牙语。默认为汉语
    # pageSize: #每页说说的显示数量
    # shuoPla: #在编辑说说的输入框中的占位符
    # avatarPla: #自定义头像url的输入框的占位符
    # motion: #加载动画的开关，1为开，0为关，默认为开
    # bgImg: #说说输入框背景图片url
    # color1: #说说背景颜色1&按钮颜色1
    # color2: #说说背景颜色2&按钮颜色2
    # color3: #说说字体颜色
    # cssUrl: #自定义css接口
  # npm i hexo-wordcount
  wordcount:
    enable: true
  clipboard:
    enable: true
  fontawesome: /libs/@fortawesome/fontawesome-pro/css/all.min.css
  fontawesome_animation:
    enable: true
    css: /libs/font-awesome-animation/font-awesome-animation.min.css # https://cdn.jsdelivr.net/gh/l-lin/font-awesome-animation/dist/font-awesome-animation.min.css
  aplayer:
    enable: true
    autoplay: false
    volume: 0.4
    order: random
    # id: 4917530132 # vol red
    # id: 4917524698 # vol blue
    # id: 76244489 # vol white
    # id: 5135845906 # for Volantis 3.0
    id: 5062959861 # TOP 30
  message:          # 音乐通知，播放、暂停、失败 时的图标
    enable: true
    icon:     # 默认图标，支持对图标添加颜色，可选值：see：/source/css/_plugins/message.styl
      default: fa-light fa-info-circle light-blue
      quection: fa-light fa-question-circle light-blue
    copyright:  # 是否在复制时弹出版权提示
      enable: true
      title: '知识共享许可协议'
      message: '请遵守 CC BY-NC-SA 4.0 协议。'
      icon: 'fa-brands fa-creative-commons light-blue'
    aplayer:
      enable: true
      play: fa-light fa-play light-blue
      pause: fa-light fa-pause light-blue
      error: fa-light fa-exclamation-square red
  darkmode:
    enable: true
  # 视差滚动效果 Slide Background
  parallax:
    enable: true

analytics:
  busuanzi: #https://cdn.jsdelivr.net/gh/volantis-x/cdn-busuanzi@2.3/js/busuanzi.pure.mini.js
  leancloud:
    app_id: YUYnaaTyd8MI9tivdEx2Ofmo-MdYXbMMI
    app_key: 3a4spbiv5QkvDhhVsXfknvRg
    custom_api_server: # 一般不需要写，除非自定义了 API Server
